{% set name = "napari-solarized" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-solarized-{{ version }}.tar.gz
  sha256: 4aac35ea6c3b7f1ff452f620868e79f040f148596f81b29bbecfd7be290bb992

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}

test:
  imports:
    - napari_solarized
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aganders3/napari-solarized
  summary: Solarized themes for napari
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aganders3
    - jaimergp
